GOOGLE_MODELS = (
    "gemini-2.5-flash",
    "gemini-2.5-flash-lite",
    "gemini-3.5-flash",
    "gemini-3.5-flash-lite",
)
GOOGLE_VERTEX_MODELS = (
    "gemini-2.5-flash",
    "gemini-2.5-flash-lite",
    "gemini-3.1-flash-lite",
    "gemini-3.5-flash",
)

GOOGLE_REALTIME_MODELS = ("gemini-3.1-flash-live-preview",)

# Full Gemini Live / native-audio prebuilt voice catalog. Each entry carries a
# commonly-perceived gender and a one-word character so the UI can show tags and
# let the user preview before choosing. Google does not officially gender these
# voices; "gender" is the widely-perceived character, offered only as a picking
# aid. All names are valid `prebuiltVoiceConfig.voiceName` values for the Live
# and TTS models, so the voice-preview endpoint can synthesize any of them.
GOOGLE_REALTIME_VOICE_DETAILS = (
    {"name": "Zephyr", "gender": "female", "characteristic": "Bright"},
    {"name": "Puck", "gender": "male", "characteristic": "Upbeat"},
    {"name": "Charon", "gender": "male", "characteristic": "Informative"},
    {"name": "Kore", "gender": "female", "characteristic": "Firm"},
    {"name": "Fenrir", "gender": "male", "characteristic": "Excitable"},
    {"name": "Leda", "gender": "female", "characteristic": "Youthful"},
    {"name": "Orus", "gender": "male", "characteristic": "Firm"},
    {"name": "Aoede", "gender": "female", "characteristic": "Breezy"},
    {"name": "Callirrhoe", "gender": "female", "characteristic": "Easy-going"},
    {"name": "Autonoe", "gender": "female", "characteristic": "Bright"},
    {"name": "Enceladus", "gender": "male", "characteristic": "Breathy"},
    {"name": "Iapetus", "gender": "male", "characteristic": "Clear"},
    {"name": "Umbriel", "gender": "male", "characteristic": "Easy-going"},
    {"name": "Algieba", "gender": "male", "characteristic": "Smooth"},
    {"name": "Despina", "gender": "female", "characteristic": "Smooth"},
    {"name": "Erinome", "gender": "female", "characteristic": "Clear"},
    {"name": "Algenib", "gender": "male", "characteristic": "Gravelly"},
    {"name": "Rasalgethi", "gender": "male", "characteristic": "Informative"},
    {"name": "Laomedeia", "gender": "female", "characteristic": "Upbeat"},
    {"name": "Achernar", "gender": "female", "characteristic": "Soft"},
    {"name": "Alnilam", "gender": "male", "characteristic": "Firm"},
    {"name": "Schedar", "gender": "male", "characteristic": "Even"},
    {"name": "Gacrux", "gender": "female", "characteristic": "Mature"},
    {"name": "Pulcherrima", "gender": "female", "characteristic": "Forward"},
    {"name": "Achird", "gender": "male", "characteristic": "Friendly"},
    {"name": "Zubenelgenubi", "gender": "male", "characteristic": "Casual"},
    {"name": "Vindemiatrix", "gender": "female", "characteristic": "Gentle"},
    {"name": "Sadachbia", "gender": "male", "characteristic": "Lively"},
    {"name": "Sadaltager", "gender": "male", "characteristic": "Knowledgeable"},
    {"name": "Sulafat", "gender": "female", "characteristic": "Warm"},
)
GOOGLE_REALTIME_VOICES = tuple(v["name"] for v in GOOGLE_REALTIME_VOICE_DETAILS)
GOOGLE_REALTIME_LANGUAGES = (
    "ar",
    "bn",
    "de",
    "en",
    "es",
    "fr",
    "gu",
    "hi",
    "id",
    "it",
    "ja",
    "kn",
    "ko",
    "ml",
    "mr",
    "nl",
    "pl",
    "pt",
    "ru",
    "ta",
    "te",
    "th",
    "tr",
    "vi",
    "zh",
)

GOOGLE_VERTEX_REALTIME_MODELS = ("google/gemini-live-2.5-flash-native-audio",)
GOOGLE_VERTEX_REALTIME_VOICES = GOOGLE_REALTIME_VOICES
GOOGLE_VERTEX_REALTIME_LANGUAGES = GOOGLE_REALTIME_LANGUAGES

GOOGLE_STT_MODELS = ("latest_long", "latest_short", "chirp_3")
# Docs-derived from Google Cloud Speech-to-Text V2 supported languages.
GOOGLE_STT_LANGUAGES = (
    "af-ZA",
    "am-ET",
    "ar-AE",
    "ar-BH",
    "ar-DZ",
    "ar-EG",
    "ar-IL",
    "ar-IQ",
    "ar-JO",
    "ar-KW",
    "ar-LB",
    "ar-MA",
    "ar-MR",
    "ar-OM",
    "ar-PS",
    "ar-QA",
    "ar-SA",
    "ar-SY",
    "ar-TN",
    "ar-XA",
    "ar-YE",
    "as-IN",
    "ast-ES",
    "az-AZ",
    "be-BY",
    "bg-BG",
    "bn-BD",
    "bn-IN",
    "bs-BA",
    "ca-ES",
    "ceb-PH",
    "ckb-IQ",
    "cmn-Hans-CN",
    "cmn-Hant-TW",
    "cs-CZ",
    "cy-GB",
    "da-DK",
    "de-AT",
    "de-CH",
    "de-DE",
    "el-GR",
    "en-AU",
    "en-GB",
    "en-HK",
    "en-IE",
    "en-IN",
    "en-NZ",
    "en-PH",
    "en-PK",
    "en-SG",
    "en-US",
    "es-419",
    "es-AR",
    "es-BO",
    "es-CL",
    "es-CO",
    "es-CR",
    "es-DO",
    "es-EC",
    "es-ES",
    "es-GT",
    "es-HN",
    "es-MX",
    "es-NI",
    "es-PA",
    "es-PE",
    "es-PR",
    "es-SV",
    "es-US",
    "es-UY",
    "es-VE",
    "et-EE",
    "eu-ES",
    "fa-IR",
    "ff-SN",
    "fi-FI",
    "fil-PH",
    "fr-BE",
    "fr-CA",
    "fr-CH",
    "fr-FR",
    "ga-IE",
    "gl-ES",
    "gu-IN",
    "ha-NG",
    "hi-IN",
    "hr-HR",
    "hu-HU",
    "hy-AM",
    "id-ID",
    "ig-NG",
    "is-IS",
    "it-CH",
    "it-IT",
    "iw-IL",
    "ja-JP",
    "jv-ID",
    "ka-GE",
    "kam-KE",
    "kea-CV",
    "kk-KZ",
    "km-KH",
    "kn-IN",
    "ko-KR",
    "ky-KG",
    "lb-LU",
    "lg-UG",
    "ln-CD",
    "lo-LA",
    "lt-LT",
    "luo-KE",
    "lv-LV",
    "mi-NZ",
    "mk-MK",
    "ml-IN",
    "mn-MN",
    "mr-IN",
    "ms-MY",
    "mt-MT",
    "my-MM",
    "ne-NP",
    "nl-BE",
    "nl-NL",
    "no-NO",
    "nso-ZA",
    "ny-MW",
    "oc-FR",
    "om-ET",
    "or-IN",
    "pa-Guru-IN",
    "pl-PL",
    "ps-AF",
    "pt-BR",
    "pt-PT",
    "ro-RO",
    "ru-RU",
    "rup-BG",
    "rw-RW",
    "sd-IN",
    "si-LK",
    "sk-SK",
    "sl-SI",
    "sn-ZW",
    "so-SO",
    "sq-AL",
    "sr-RS",
    "ss-Latn-ZA",
    "st-ZA",
    "su-ID",
    "sv-SE",
    "sw",
    "sw-KE",
    "ta-IN",
    "te-IN",
    "tg-TJ",
    "th-TH",
    "tn-Latn-ZA",
    "tr-TR",
    "ts-ZA",
    "uk-UA",
    "umb-AO",
    "ur-PK",
    "uz-UZ",
    "ve-ZA",
    "vi-VN",
    "wo-SN",
    "xh-ZA",
    "yo-NG",
    "yue-Hant-HK",
    "zu-ZA",
)

GOOGLE_TTS_MODELS = ("chirp_3_hd",)
GOOGLE_TTS_VOICES = ("en-US-Chirp3-HD-Charon",)
GOOGLE_TTS_LANGUAGES = (
    "ar-XA",
    "bn-IN",
    "bg-BG",
    "yue-HK",
    "hr-HR",
    "cs-CZ",
    "da-DK",
    "nl-BE",
    "nl-NL",
    "en-AU",
    "en-IN",
    "en-GB",
    "en-US",
    "et-EE",
    "fi-FI",
    "fr-CA",
    "fr-FR",
    "de-DE",
    "el-GR",
    "gu-IN",
    "he-IL",
    "hi-IN",
    "hu-HU",
    "id-ID",
    "it-IT",
    "ja-JP",
    "kn-IN",
    "ko-KR",
    "lv-LV",
    "lt-LT",
    "ml-IN",
    "cmn-CN",
    "mr-IN",
    "nb-NO",
    "pl-PL",
    "pt-BR",
    "pa-IN",
    "ro-RO",
    "ru-RU",
    "sr-RS",
    "sk-SK",
    "sl-SI",
    "es-ES",
    "es-US",
    "sw-KE",
    "sv-SE",
    "ta-IN",
    "te-IN",
    "th-TH",
    "tr-TR",
    "uk-UA",
    "ur-IN",
    "vi-VN",
)
